### ISSUE TITLE
Crash when try to search video ..

### ISSUE THREAD

**Issue by fairbird** [Taapat/enigma2-plugin-youtube#32]
> Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 65, in action
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 46, in action
  File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/YouTubeSearch.py", line 37, in okClicked
  File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/YouTubeSearch.py", line 312, in getSuggestions
  File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/YouTubeSearch.py", line 341, in getGoogleSuggestions
NameError: global name 'gaierror' is not defined

**Comment by Taapat** [comment]
Thx, for report!
