### ISSUE TITLE
after recent changes, download not work !

### ISSUE THREAD

**Issue by thawtes** [Taapat/enigma2-plugin-youtube#77]
hi, @Taapat 
pls, look at below logs

`05:39:15.1361 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:39:15+0300 [-] KEY: 352 1 KEY_OK OK
05:39:32.0794 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:39:32+0300 [-] job [YouTube] Video download failed
05:39:32.0816 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:39:32+0300 [-] [YouTube] 'utf8' codec can't decode bytes in position 43-44: invalid continuation byte
05:39:32.0908 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:39:32+0300 [HTTPPageDownloader (TLSMemoryBIOProtocol),client] Unhandled Error
05:39:33.0168 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:39:33+0300 [-]   File "/home/oe1/atv64/build-enviroment/builds/openatv/release/vuduo2/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-youtube/gitAUTOINC+4f1fcc5e04-r0/git/src/YouTubeDownload.py", line 182, in updateDownloadList
05:39:33.0192 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:39:33+0300 [-]   File "/usr/lib/enigma2/python/Components/Task.py", line 35, in getProgress
05:39:33.0217 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:39:33+0300 [-] IndexError: list index out of range
05:39:33.0221 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method YouTubeDownloadList.updateDownloadList of <class 'Plugins.Extensions.YouTube.YouTubeDownload.YouTubeDownloadList'>>,()) failed)`

`05:41:22.5924 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-] [SCREENNAME]  YouTubeMain
05:41:22.6031 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-] [Skin] Processing screen 'YouTubeDownloadList', position=(0, 0), size=(1920 x 1080) for module 'YouTubeDownloadList'.
05:41:22.6598 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-] [SCREENNAME]  YouTubeMain
05:41:22.6656 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-] Traceback (most recent call last):
05:41:22.6675 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/usr/lib/enigma2/python/mytest.py", line 248, in processDelay
05:41:22.6698 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]     callback(*retval)
05:41:22.6717 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/home/oe1/atv64/build-enviroment/builds/openatv/release/vuduo2/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-youtube/gitAUTOINC+4f1fcc5e04-r0/git/src/YouTubeUi.py", line 1201, in menuCallback
05:41:22.6738 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/usr/lib/enigma2/python/mytest.py", line 345, in open
05:41:22.6761 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]     dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
05:41:22.6778 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/usr/lib/enigma2/python/mytest.py", line 280, in instantiateDialog
05:41:22.6801 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
05:41:22.6818 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/usr/lib/enigma2/python/mytest.py", line 309, in doInstantiateDialog
05:41:22.6841 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]     dlg.applySkin()
05:41:22.6858 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/usr/lib/enigma2/python/Components/GUISkin.py", line 114, in applySkin
05:41:22.6879 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/usr/lib/enigma2/python/Components/GUISkin.py", line 47, in createGUIScreen
05:41:22.6899 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/home/oe1/atv64/build-enviroment/builds/openatv/release/vuduo2/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-youtube/gitAUTOINC+4f1fcc5e04-r0/git/src/YouTubeDownload.py", line 173, in layoutFinished
05:41:22.6918 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/home/oe1/atv64/build-enviroment/builds/openatv/release/vuduo2/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-youtube/gitAUTOINC+4f1fcc5e04-r0/git/src/YouTubeDownload.py", line 182, in updateDownloadList
05:41:22.6938 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/usr/lib/enigma2/python/Components/Task.py", line 35, in getProgress
05:41:22.6959 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-] IndexError: list index out of range
05:41:22.6963 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method Session.processDelay of <__main__.Session instance at 0x72291148>>,()) failed)`

`05:41:22.5787 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-] [ActionMap] Keymap 'WizardActions' -> Action = 'ok'.
05:41:22.5835 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-] [SCREENNAME]  ['YouTubeMain_summary', 'SimpleSummary']
05:41:22.5924 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-] [SCREENNAME]  YouTubeMain
05:41:22.6031 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-] [Skin] Processing screen 'YouTubeDownloadList', position=(0, 0), size=(1920 x 1080) for module 'YouTubeDownloadList'.
05:41:22.6598 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-] [SCREENNAME]  YouTubeMain
05:41:22.6656 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-] Traceback (most recent call last):
05:41:22.6675 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/usr/lib/enigma2/python/mytest.py", line 248, in processDelay
05:41:22.6698 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]     callback(*retval)
05:41:22.6717 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/home/oe1/atv64/build-enviroment/builds/openatv/release/vuduo2/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-youtube/gitAUTOINC+4f1fcc5e04-r0/git/src/YouTubeUi.py", line 1201, in menuCallback
05:41:22.6738 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/usr/lib/enigma2/python/mytest.py", line 345, in open
05:41:22.6761 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]     dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
05:41:22.6778 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/usr/lib/enigma2/python/mytest.py", line 280, in instantiateDialog
05:41:22.6801 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
05:41:22.6818 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/usr/lib/enigma2/python/mytest.py", line 309, in doInstantiateDialog
05:41:22.6841 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]     dlg.applySkin()
05:41:22.6858 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/usr/lib/enigma2/python/Components/GUISkin.py", line 114, in applySkin
05:41:22.6879 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/usr/lib/enigma2/python/Components/GUISkin.py", line 47, in createGUIScreen
05:41:22.6899 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/home/oe1/atv64/build-enviroment/builds/openatv/release/vuduo2/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-youtube/gitAUTOINC+4f1fcc5e04-r0/git/src/YouTubeDownload.py", line 173, in layoutFinished
05:41:22.6918 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/home/oe1/atv64/build-enviroment/builds/openatv/release/vuduo2/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-youtube/gitAUTOINC+4f1fcc5e04-r0/git/src/YouTubeDownload.py", line 182, in updateDownloadList
05:41:22.6938 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-]   File "/usr/lib/enigma2/python/Components/Task.py", line 35, in getProgress
05:41:22.6959 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-07 05:41:22+0300 [-] IndexError: list index out of range
05:41:22.6963 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method Session.processDelay of <__main__.Session instance at 0x72291148>>,()) failed)`

**Comment by thawtes** [comment]
I'll check again to make sure ...
