### ISSUE TITLE
Crash when downloading a video ( new log)

### ISSUE THREAD

**Issue by ozone1864** [Taapat/enigma2-plugin-youtube#83]
Dear @Taapat ,
Previously we checked the issue and openATV seems that they solved the issue.
Now the system crashes when checking download page while downloading a video
but with new error.
Hardware: Zgemma H9S
Software: OpenAtv 6.3 latest version stable (26-05-2020)
[enigma2_crash_1590487762.log](https://github.com/Taapat/enigma2-plugin-youtube/files/4682022/enigma2_crash_1590487762.log)
[enigma2_crash_1590488006.log](https://github.com/Taapat/enigma2-plugin-youtube/files/4682023/enigma2_crash_1590488006.log)

Regards,

**Comment by Taapat** [comment]
Do you get this crash every time when checking download page or just sometimes?

**Comment by ozone1864** [comment]
hey @Taapat ,
sometimes but like happening alot.

**Comment by Taapat** [comment]
Try add all changes from this commit also in downloadWithProgress: https://github.com/OpenPLi/enigma2/commit/bcfdaae#diff-e160c4fd78027d857bb6afa6f49756acL58-R71

openATV added only changes in HTTPProgressDownloader.

**Comment by ozone1864** [comment]
Ah ok will test

**Comment by ozone1864** [comment]
@Taapat I cant edit from my side seems encoding issue, any secondary solution ?

**Comment by Taapat** [comment]
Download this file form OpenPli, put in your recievier and restart enigma: https://raw.githubusercontent.com/OpenPLi/enigma2/develop/lib/python/Tools/Downloader.py

**Comment by ozone1864** [comment]
Blue screen again
[enigma2_crash_1590504341.log](https://github.com/Taapat/enigma2-plugin-youtube/files/4683003/enigma2_crash_1590504341.log)

**Comment by jbleyel** [comment]
Hi @Taapat, this is not a downloader issue.
It looks like an encoding problem.

```
job [YouTube] Video download failed
17:45:41.0284 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-26 17:45:41+0300 [-] [YouTube] 'utf8' codec can't decode byte 0xd9 in position 44: invalid continuation byte
17:45:41.1538 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-26 17:45:41+0300 [-] Traceback (most recent call last):
17:45:41.1543 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-26 17:45:41+0300 [-]   File "/home/oe1/atv63/build-enviroment/builds/openatv/release/h9/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-youtube/gitAUTOINC+1f8bc35b17-r0/git/src/YouTubeDownload.py", line 182, in updateDownloadList
17:45:41.1551 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-26 17:45:41+0300 [-]   File "/usr/lib/enigma2/python/Components/Task.py", line 35, in getProgress
17:45:41.1557 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-26 17:45:41+0300 [-] IndexError: list index out of range

```
