### ISSUE TITLE
Latest version causes enigma2 crash

### ISSUE THREAD

**Issue by petrkr** [Taapat/enigma2-plugin-youtube#91]
http://taapat.ho.ua/enigma2-plugin-youtube/enigma2-plugin-extensions-youtube_h1+git524+d6a7070-r0.0_all.ipk

PurE2

Log
```
20:24:38.5933 {   } Components/ActionMap.py:56 action [ActionMap] Keymap 'SetupActions' -> Action = 'ok'.
20:24:38.5971 { D } Traceback (most recent call last):
20:24:38.5972 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 57, in action
20:24:38.5974 { D }   File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 167, in save
20:24:38.5975 { D }   File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 171, in run
20:24:38.5976 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/plugin.py", line 8, in main
20:24:38.5978 { D }     from .YouTubeUi import YouTubeMain
20:24:38.5978 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/YouTubeUi.py", line 28, in <module>
20:24:38.5979 { D }     from . import _, ngettext
20:24:38.5980 { D } ImportError: cannot import name ngettext
20:24:38.5981 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0xa2c54210>>,('SetupActions', 'ok')) failed)
```

**Comment by Taapat** [comment]
Try remove, and after that install plugin again.
The package contains the correct files, but your error indicates that your receiver does not have a "__init__" file from the package.

**Comment by petrkr** [comment]
Installed older version "http://taapat.ho.ua/enigma2-plugin-youtube/enigma2-plugin-extensions-youtube_h1+git521+330d1ca-r0.0_all.ipk" and now back latest and it works now...

Also tried remove and install again,, also works... So probably fixed by that removed/installed

Closing now
